[tox]
isolated_build = true
minversion = 4.22
envlist =
    py{310,311,312,313,314}
    cover-{clean,report}
    lint
    mypy

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
dependency_groups = pytest
passenv =
    BARNHUNT_MOCK_WIN32
    GITHUB_TOKEN
    INKSCAPE_COMMAND
commands =
    coverage run -m pytest {posargs:tests -ra}

depends =
    py{310,311,312,313,314}: cover-clean
    cover-report: py{310,311,312,313,314}

[testenv:cover-clean]
deps = coverage[toml]
skip_install = true
commands = coverage erase

[testenv:cover-report]
deps = coverage[toml]
skip_install = true
commands =
    -coverage combine --append
    coverage xml
    coverage html
    coverage report --fail-under=100

[testenv:lint]
skip_install = true
basepython = py314, py313, py312, py311, py310
deps =
    build
    twine

commands =
    python -m build --sdist --outdir {envtmpdir}/dist {toxinidir}
    twine check {envtmpdir}/dist/*

[testenv:mypy]
usedevelop = true
basepython = py314, py313, py312, py311, py310
dependency_groups =
    mypy
    pytest
commands =
    mypy barnhunt tests
