name: CI

on:
  push:
    branches:
      - '*'
    tags:
      # v* are protected tags
      - 'v*'
  pull_request:

permissions:
  contents: read

jobs:

  tests:
    name: Run Tests and Build Python Dist
    uses: ./.github/workflows/tests.yml

  oxidize:
    name: Build & Test Windows Installer
    uses: ./.github/workflows/oxidize.yml

  pypi-publish:
    name: Upload to PyPI
    needs: [tests, oxidize]
    if: contains(fromJSON('["pre", "release"]'), needs.tests.outputs.version-type)
    environment:
      name: pypi
      url: https://pypi.org/p/barnhunt
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1

  gh-release:
    name: Post GH Release
    needs: [tests, oxidize, pypi-publish]
    if: contains(fromJSON('["pre", "release"]'), needs.tests.outputs.version-type)
    permissions:
      contents: write           # to create GH release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: oxidized
      - uses: softprops/action-gh-release@v1
        with:
          files: '*.msi'
          fail_on_unmatched_files: false
          generate_release_notes: true
          prerelease: ${{ needs.tests.outputs.version-type != 'release' }}
