name: CI

on:
  push:
    branches:
      - '*'
    tags:
      # v* are protected tags
      - 'v*'
  pull_request:

permissions:
  contents: read

jobs:

  tests:
    name: Run Tests and Build Python Dist
    uses: ./.github/workflows/tests.yml

  pypi-publish:
    name: Upload to PyPI
    needs: [tests]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    environment:
      name: pypi
      url: https://pypi.org/p/barnhunt
    permissions:
      id-token: write           # needed to publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # @v8.0.1
        with:
          name: dist
          path: dist
      - uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # @release/v1.14.0
        with:
          skip-existing: true

  gh-release:
    name: Post GH Release
    needs: [tests, pypi-publish]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write           # to create GH release
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda #@v3.0.0
        with:
          generate_release_notes: true
          prerelease: ${{ needs.tests.outputs.version-type != 'release' }}
