name: Tests

on:
  - push
  - pull_request

env:
  'default-python-version': '3.10'

jobs:
  tests:
    name: Tox tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        include:
          - python-version: '3.10'
            install-inkscape: true
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install inkscape
      if: matrix.install-inkscape
      run: sudo apt install -y inkscape

    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Test with tox
      run: tox

    - uses: actions/upload-artifact@v3
      with:
        name: coverage-data
        path: .coverage.*

  coverage:
    name: Coverage Report
    needs: tests
    if: always()
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ env.default-python-version }}
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - uses: actions/download-artifact@v2
      with:
        name: coverage-data
    - name: Test coverage
      run: tox -e cover-report
    - name: Upload HTML coverage report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: htmlcov
        path: htmlcov

  lint:
    name: Lint Checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ env.default-python-version }}
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Lint
      run: tox -e lint
    - name: Mypy
      if: always()
      run: tox -e mypy
